package view;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class LauncherSystem extends javax.swing.JFrame {

    private ImageIcon imagen;
    private Icon ico;

    public LauncherSystem() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Sistema de inventario La Ermita".toUpperCase());
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Ico.png")).getImage());

    }

    private MenuPrincipal menu_principal;

    public void setVentana(MenuPrincipal principal) {
        this.menu_principal = menu_principal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        icoP = new javax.swing.JLabel();
        inicio = new javax.swing.JLabel();
        TextUsuario = new javax.swing.JLabel();
        TextPassword = new javax.swing.JLabel();
        UsuarioLogin = new javax.swing.JTextField();
        ClaveLogin = new javax.swing.JPasswordField();
        ENTERBOTTON = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icoP.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        icoP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icoP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ico.png"))); // NOI18N
        icoP.setText("LA ERMITA");
        jPanelFondo.add(icoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 330, -1));

        inicio.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        inicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inicio.setText("INICIO SESION");
        jPanelFondo.add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 430, -1));

        TextUsuario.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        TextUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextUsuario.setText("USUARIO");
        jPanelFondo.add(TextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 460, -1));

        TextPassword.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        TextPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextPassword.setText("CONTRASEÑA");
        jPanelFondo.add(TextPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 450, -1));

        UsuarioLogin.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        UsuarioLogin.setForeground(new java.awt.Color(102, 102, 102));
        UsuarioLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UsuarioLogin.setText("Ingrese su nombre de usuario");
        UsuarioLogin.setBorder(null);
        UsuarioLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UsuarioLoginMousePressed(evt);
            }
        });
        UsuarioLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioLoginActionPerformed(evt);
            }
        });
        jPanelFondo.add(UsuarioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 290, 40));

        ClaveLogin.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        ClaveLogin.setForeground(new java.awt.Color(102, 102, 102));
        ClaveLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ClaveLogin.setText("***");
        ClaveLogin.setBorder(null);
        ClaveLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClaveLoginMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ClaveLoginMousePressed(evt);
            }
        });
        ClaveLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClaveLoginActionPerformed(evt);
            }
        });
        ClaveLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ClaveLoginKeyPressed(evt);
            }
        });
        jPanelFondo.add(ClaveLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 240, 40));

        ENTERBOTTON.setText("ENTER");
        ENTERBOTTON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ENTERBOTTONMouseClicked(evt);
            }
        });
        ENTERBOTTON.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ENTERBOTTONKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ENTERBOTTONKeyReleased(evt);
            }
        });
        jPanelFondo.add(ENTERBOTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 340, 170, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuarioLoginMousePressed
        if (UsuarioLogin.getText().equals("Ingrese su nombre de usuario")) {
            UsuarioLogin.setText("");
            UsuarioLogin.setForeground(Color.BLACK);
        }
        if (String.valueOf(ClaveLogin.getPassword()).isEmpty()) {
            ClaveLogin.setText("***");
            ClaveLogin.setForeground(Color.gray);
        }
    }//GEN-LAST:event_UsuarioLoginMousePressed

    private void UsuarioLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioLoginActionPerformed

    private void ClaveLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClaveLoginMousePressed
        if (String.valueOf(ClaveLogin.getPassword()).equals("***")) {
            ClaveLogin.setText("");
            ClaveLogin.setForeground(Color.black);
        }
        if (UsuarioLogin.getText().isEmpty()) {
            UsuarioLogin.setText("Ingrese su nombre de usuario");
            UsuarioLogin.setForeground(Color.gray);
        }
    }//GEN-LAST:event_ClaveLoginMousePressed

    private void ClaveLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClaveLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClaveLoginActionPerformed

    private void ClaveLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClaveLoginMouseClicked
        if (String.valueOf(ClaveLogin.getPassword()).equals("***")) {
            ClaveLogin.setText("");
            ClaveLogin.setForeground(Color.black);
        }
        if (UsuarioLogin.getText().isEmpty()) {
            UsuarioLogin.setText("Ingrese su nombre de usuario");
            UsuarioLogin.setForeground(Color.gray);
        }


    }//GEN-LAST:event_ClaveLoginMouseClicked

    private void ENTERBOTTONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ENTERBOTTONMouseClicked
        if (UsuarioLogin.getText().equals("admin".toLowerCase())) {
            if (ClaveLogin.getText().equals("123")) {
                MenuPrincipal Principal = new MenuPrincipal();
                Principal.setVentana(Principal);
                Principal.setVisible(true);
                this.setVentana(Principal);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this, "Datos Incorrectos ", "LOGIN", JOptionPane.INFORMATION_MESSAGE);
                UsuarioLogin.setText("Ingrese su nombre de usuario");
                ClaveLogin.setText("***");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Datos Incorrectos", "LOGIN", JOptionPane.INFORMATION_MESSAGE);
            UsuarioLogin.setText("Ingrese su nombre de usuario");
            ClaveLogin.setText("***");
        }
    }//GEN-LAST:event_ENTERBOTTONMouseClicked

    private void ENTERBOTTONKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ENTERBOTTONKeyPressed
        ENTER();
    }//GEN-LAST:event_ENTERBOTTONKeyPressed

    private void ENTERBOTTONKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ENTERBOTTONKeyReleased

    }//GEN-LAST:event_ENTERBOTTONKeyReleased

    private void ClaveLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ClaveLoginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ENTERBOTTON.requestFocus();
            ENTERBOTTON.doClick();
        }

    }//GEN-LAST:event_ClaveLoginKeyPressed

    private void ENTER() {
        if (UsuarioLogin.getText().equals("admin".toLowerCase())) {
            if (ClaveLogin.getText().equals("123")) {
                MenuPrincipal Principal = new MenuPrincipal();
                Principal.setVentana(Principal);
                Principal.setVisible(true);
                this.setVentana(Principal);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this, "Datos Incorrectos ", "LOGIN", JOptionPane.INFORMATION_MESSAGE);
                UsuarioLogin.setText("Ingrese su nombre de usuario");
                ClaveLogin.setText("***");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Datos Incorrectos", "LOGIN", JOptionPane.INFORMATION_MESSAGE);
            UsuarioLogin.setText("Ingrese su nombre de usuario");
            ClaveLogin.setText("***");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LauncherSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LauncherSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LauncherSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LauncherSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LauncherSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ClaveLogin;
    private javax.swing.JButton ENTERBOTTON;
    private javax.swing.JLabel TextPassword;
    private javax.swing.JLabel TextUsuario;
    private javax.swing.JTextField UsuarioLogin;
    private javax.swing.JLabel icoP;
    private javax.swing.JLabel inicio;
    private javax.swing.JPanel jPanelFondo;
    // End of variables declaration//GEN-END:variables
}
