package view;

import controller.ProductoController;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class MenuVenta extends javax.swing.JFrame {

    private final ProductoController PRODUCTO_CONTROLLER = new ProductoController();
    private final String[] Columnas = {"Producto".toUpperCase(), "Id Producto".toUpperCase(), "Descripcion".toUpperCase(), "Proveedor".toUpperCase(), "Categoria".toUpperCase(), "Cantidad".toUpperCase(),
        "Precio de compra".toUpperCase(), "Precio de venta".toUpperCase()};
    private final DefaultTableModel TABLA_DEFECTO = new DefaultTableModel(null, Columnas);
    private final String[] columnasVenta = {"Producto".toUpperCase(), "Precio de venta".toUpperCase(), "Cantidad".toUpperCase()};
    private final DefaultTableModel tablaVenta = new DefaultTableModel(null, columnasVenta);
    private ArrayList<String[]> listaVenta = new ArrayList<>();

    public TableRowSorter filtroS;
    String filtro;

    public MenuVenta() {
        initComponents();
        generarTabla();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Sistema de inventario La Ermita".toUpperCase());
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Ico.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelCedulaCliente = new javax.swing.JLabel();
        jTextFieldBUSCAR = new javax.swing.JTextField();
        jLabelCantidad1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSpinnerCantidad = new javax.swing.JSpinner();
        jTextFieldCC = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsulta = new javax.swing.JTable();
        jLabelNombre1 = new javax.swing.JLabel();
        jTextFieldProducto = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonPagar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonCarrito = new javax.swing.JButton();
        FACTURA = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelFactura = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProductosVenta = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextNombreCliente = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelNombreClienteP1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();
        jTextFieldNombreCliente = new javax.swing.JTextField();
        jLabelNombre2 = new javax.swing.JLabel();
        jTextFieldVenta = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItemVentas = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuSoporte = new javax.swing.JMenu();
        jMenuItemAcercadeNosostros = new javax.swing.JMenuItem();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCedulaCliente.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabelCedulaCliente.setText("CEDULA:");
        jPanel1.add(jLabelCedulaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 40));

        jTextFieldBUSCAR.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        jTextFieldBUSCAR.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldBUSCAR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBUSCAR.setText("BARRA DE BUSQUEDA");
        jTextFieldBUSCAR.setToolTipText("");
        jTextFieldBUSCAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldBUSCARMouseClicked(evt);
            }
        });
        jTextFieldBUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBUSCARActionPerformed(evt);
            }
        });
        jTextFieldBUSCAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBUSCARKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 520, 30));

        jLabelCantidad1.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabelCantidad1.setText("CANTIDAD:");
        jPanel1.add(jLabelCantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel10.setText("PRECIO DE VENTA:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 160, -1));

        jSpinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));
        jPanel1.add(jSpinnerCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 220, -1));

        jTextFieldCC.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jTextFieldCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCCActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 370, -1));

        jTableConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableConsulta);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 580, 140));

        jLabelNombre1.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabelNombre1.setText("PRODUCTO:");
        jPanel1.add(jLabelNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 40));

        jTextFieldProducto.setEditable(false);
        jTextFieldProducto.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jTextFieldProducto.setFocusable(false);
        jPanel1.add(jTextFieldProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 370, -1));

        jButtonCancelar.setText("CANCELAR");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 120, -1));

        jButtonPagar.setText("PAGAR");
        jButtonPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPagarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonPagarMouseEntered(evt);
            }
        });
        jButtonPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPagarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 130, -1));

        jButtonLimpiar.setText("LIMPIAR");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 120, -1));

        jButtonCarrito.setText("CARRITO");
        jButtonCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarritoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 90, 30));

        FACTURA.setBackground(new java.awt.Color(255, 255, 255));
        FACTURA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        FACTURA.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 307, -1, -1));

        jLabelFactura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FACTURA.add(jLabelFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 638, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        FACTURA.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 307, -1, 193));

        jLabel1.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INFORMACION FACTURACION");
        jLabel1.setToolTipText("");
        FACTURA.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jTableProductosVenta.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTableProductosVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableProductosVenta);

        FACTURA.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 300, 200));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jTextFieldPrecio.setEditable(false);
        jTextFieldPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPrecio.setText("0.0");
        jTextFieldPrecio.setFocusable(false);
        jTextFieldPrecio.setPreferredSize(new java.awt.Dimension(60, 25));
        jTextFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioActionPerformed(evt);
            }
        });

        jTextFieldTotal.setEditable(false);
        jTextFieldTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTotal.setText("0.0");
        jTextFieldTotal.setFocusable(false);
        jTextFieldTotal.setPreferredSize(new java.awt.Dimension(60, 25));
        jTextFieldTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TOTAL:");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("IVA:");

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PRECIO:");

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("15%");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        FACTURA.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 300, 170));

        TextNombreCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FACTURA.add(TextNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 2, 10)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(" ALM ERMITA AP LT A");
        FACTURA.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 180, -1));

        jLabelNombreClienteP1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabelNombreClienteP1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNombreClienteP1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        FACTURA.add(jLabelNombreClienteP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 290, 80));

        jPanel1.add(FACTURA, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 310, 500));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("CANTIDAD DISPONIBLE:");
        jLabel2.setPreferredSize(new java.awt.Dimension(55, 25));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 190, -1));

        jTextFieldCantidad.setEditable(false);
        jTextFieldCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCantidad.setFocusable(false);
        jTextFieldCantidad.setPreferredSize(new java.awt.Dimension(70, 25));
        jTextFieldCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 220, -1));

        jTextFieldNombreCliente.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jTextFieldNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreClienteActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 370, -1));

        jLabelNombre2.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabelNombre2.setText("CLIENTE:");
        jPanel1.add(jLabelNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        jTextFieldVenta.setEditable(false);
        jTextFieldVenta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldVenta.setFocusable(false);
        jTextFieldVenta.setPreferredSize(new java.awt.Dimension(70, 25));
        jTextFieldVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVentaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 250, -1));

        jTabbedPane1.addTab("Realizar Venta", jPanel1);

        jMenu1.setText("Sistema");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("Cerrar Sistema");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu6.setText("Ventas / Cotizacion ");

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem10.setText("Menu Principal");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem10);

        jMenuItemVentas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemVentas.setText("Ventas");
        jMenuItemVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVentasActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemVentas);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Cotizacion");
        jMenuItem2.setToolTipText("");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);
        jMenu6.add(jSeparator3);

        jMenuBar1.add(jMenu6);

        jMenu5.setText("Proveedor ");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Abrir Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        jMenuSoporte.setText("Soporte");

        jMenuItemAcercadeNosostros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemAcercadeNosostros.setText("Acerca de nosostros");
        jMenuItemAcercadeNosostros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcercadeNosostrosActionPerformed(evt);
            }
        });
        jMenuSoporte.add(jMenuItemAcercadeNosostros);

        jMenuBar1.add(jMenuSoporte);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 884, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreClienteActionPerformed

    private void jTextFieldCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadActionPerformed

    private void jTextFieldTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalActionPerformed

    private void jTextFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioActionPerformed

    private void jButtonCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarritoActionPerformed
        int cantidadAVender = (int) jSpinnerCantidad.getValue();

        if (cantidadAVender == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese una cantidad válida");
        } else {
            try {
                int indice = jTableConsulta.getSelectedRow();
                if (indice == -1) {
                    JOptionPane.showMessageDialog(null, "Seleccione un producto de la tabla");
                    return;
                }

                if (jTextFieldNombreCliente.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Introduzca nombre es obligatorio");
                    return;
                }

                if (jTextFieldCC.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "El campo de cédula del cliente no puede estar vacío");
                    return;
                }

                jLabelNombreClienteP1.setText("<html>"
                        + "<b>Nombre del cliente:</b><br>"
                        + jTextFieldNombreCliente.getText()
                        + "<br>" + "<b>Cedula del cliente:</b><br>"
                        + jTextFieldCC.getText() + "</html>");

                int cantidadDisponible = Integer.parseInt(jTableConsulta.getValueAt(indice, 5).toString()); // Columna de cantidad
                if (cantidadAVender <= cantidadDisponible) {
                    // Restar la cantidad vendida de la cantidad disponible
                    int cantidadRestante = cantidadDisponible - cantidadAVender;
                    jTableConsulta.setValueAt(cantidadRestante, indice, 5); // Actualizar la cantidad en la tabla

                    // Añadir producto a la lista de ventas
                    listaVenta.add(new String[]{jTextFieldProducto.getText(),
                        jTextFieldVenta.getText(),
                        String.valueOf(jSpinnerCantidad.getValue())});
                    generarTablaVenta();

                    float precio = Float.parseFloat((String) jTextFieldPrecio.getText());
                    System.out.println(precio);
                    float costeProducto = Float.parseFloat(jTextFieldVenta.getText()) * cantidadAVender;
                    System.out.println(costeProducto);
                    float nuevoPrecio = precio + costeProducto;
                    System.out.println(nuevoPrecio);
                    String precioString = String.valueOf(nuevoPrecio);
                    jTextFieldPrecio.setText(precioString);
                    float precioIVA = nuevoPrecio * 0.15f;
                    float precioTOTAL = nuevoPrecio + precioIVA;
                    jTextFieldTotal.setText(String.valueOf(precioTOTAL));
                    jTextFieldCantidad.setText(String.valueOf(cantidadDisponible - cantidadAVender));
                } else {
                    JOptionPane.showMessageDialog(null, "Cantidad insuficiente en inventario");
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonCarritoActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        jTextFieldCC.setText("");
        jTextFieldNombreCliente.setText("");
        jTextFieldProducto.setText("");
        jSpinnerCantidad.setValue(0);
        jTextFieldCantidad.setText("");
        jTextFieldVenta.setText("");
        jLabelFactura.setText("");
        jTableProductosVenta.clearSelection();
        jTextFieldBUSCAR.setText("");
        jLabelNombreClienteP1.setText("");
        DefaultTableModel modelo = (DefaultTableModel) jTableProductosVenta.getModel();
        modelo.setRowCount(0);
        jTextFieldTotal.setText("0.0");
        jTextFieldPrecio.setText("0.0");
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
       MenuPrincipal menu_principal = new MenuPrincipal();
        menu_principal.setVentana(menu_principal);
        menu_principal.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTableConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultaMouseClicked
        try {
            int indice = jTableConsulta.rowAtPoint(evt.getPoint());
            if (indice >= 0 && indice < jTableConsulta.getRowCount()) {
                jTextFieldProducto.setText(String.valueOf(jTableConsulta.getValueAt(indice, 0)));
                jTextFieldCantidad.setText(String.valueOf(jTableConsulta.getValueAt(indice, 5)));
                jTextFieldVenta.setText(String.valueOf(jTableConsulta.getValueAt(indice, 7)));

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al seleccionar el producto " + e.getMessage());
        }
    }//GEN-LAST:event_jTableConsultaMouseClicked

    private void jTextFieldCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCCActionPerformed

    private void jTextFieldBUSCARKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBUSCARKeyTyped
        filtroS = new TableRowSorter(jTableConsulta.getModel());
        jTableConsulta.setRowSorter(filtroS);
    }//GEN-LAST:event_jTextFieldBUSCARKeyTyped

    private void jTextFieldBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBUSCARActionPerformed

    }//GEN-LAST:event_jTextFieldBUSCARActionPerformed

    private void jTextFieldBUSCARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldBUSCARMouseClicked
        try {
            jTextFieldBUSCAR.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) {
                    try {
                        String cadena = jTextFieldBUSCAR.getText();
                        jTextFieldBUSCAR.setText(cadena);
                        repaint();
                        filtro();
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }

            });
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTextFieldBUSCARMouseClicked

    private void jButtonPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPagarActionPerformed

    private void jButtonPagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPagarMouseClicked
        for (String[] producto : listaVenta) {
            int cantidadProductos = jTableConsulta.getRowCount();
            String nombreProducto = producto[0];
            for (int i = 0; i < cantidadProductos; i++) {
                if (jTableConsulta.getValueAt(i, 0).equals(nombreProducto)) {
                    String nombre = (String) jTableConsulta.getValueAt(i, 0);
                    String StringID = (String) jTableConsulta.getValueAt(i, 1);
                    int IdProducto = Integer.parseInt(StringID);
                    String descripcion = (String) jTableConsulta.getValueAt(i, 2);
                    String proveedor = (String) jTableConsulta.getValueAt(i, 3);
                    String categoria = (String) jTableConsulta.getValueAt(i, 4);
                    int cantidad = (int) jTableConsulta.getValueAt(i, 5);
                    String strPrecioCompra = (String) jTableConsulta.getValueAt(i, 6);
                    int precioCompra = Integer.parseInt(strPrecioCompra);
                    String strPrecioVenta = (String) jTableConsulta.getValueAt(i, 7);
                    int precioVenta = Integer.parseInt(strPrecioVenta);

                    PRODUCTO_CONTROLLER.producto_model.setNombre_producto(nombre);
                    PRODUCTO_CONTROLLER.producto_model.setIdProducto(IdProducto);
                    PRODUCTO_CONTROLLER.producto_model.setDescripcion(descripcion);
                    PRODUCTO_CONTROLLER.producto_model.setProveedor(proveedor);
                    PRODUCTO_CONTROLLER.producto_model.setCategoria(categoria);
                    PRODUCTO_CONTROLLER.producto_model.setCantidad(cantidad);
                    PRODUCTO_CONTROLLER.producto_model.setPrecio_compra(precioCompra);
                    PRODUCTO_CONTROLLER.producto_model.setPrecio_venta(precioVenta);
                    PRODUCTO_CONTROLLER.actualizarArchivoVenta(PRODUCTO_CONTROLLER.producto_model, nombre);
                }
            }

        }
        PRODUCTO_CONTROLLER.generarFactura(PRODUCTO_CONTROLLER.producto_model, jTextFieldNombreCliente.getText(), jTextFieldCC.getText(), listaVenta, jTextFieldPrecio.getText(), jTextFieldTotal.getText());
    }//GEN-LAST:event_jButtonPagarMouseClicked

    private void jTextFieldVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVentaActionPerformed

    private void jButtonPagarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPagarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPagarMouseEntered

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JOptionPane.showMessageDialog(null, "CERRAR SESSION");
        LauncherSystem login = new LauncherSystem();
        login.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        MenuPrincipal menu_principal = new MenuPrincipal();
        menu_principal.setVentana(menu_principal);
        menu_principal.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItemVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVentasActionPerformed
        MenuVenta venta = new MenuVenta();
        venta.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItemVentasActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        MenuCotizacion Cotizacion = new MenuCotizacion();
        Cotizacion.setVentana(Cotizacion);
        Cotizacion.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        MenuProveedor Proveedor = new MenuProveedor();
        Proveedor.setVentana(Proveedor);
        Proveedor.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemAcercadeNosostrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcercadeNosostrosActionPerformed
        JOptionPane.showMessageDialog(null, "GRACIAS POR CONFIAR EN NOSOTROS");
    }//GEN-LAST:event_jMenuItemAcercadeNosostrosActionPerformed

    private void generarTabla() {
        TABLA_DEFECTO.setRowCount(0);
        for (String[] datos : PRODUCTO_CONTROLLER.mostarProductoTabla()) {
            TABLA_DEFECTO.addRow(datos);
        }
        jTableConsulta.setModel(TABLA_DEFECTO);
        System.out.println(Arrays.deepToString(PRODUCTO_CONTROLLER.mostarProductoTabla().toArray()));
    }

    public void filtro() {
        filtro = jTextFieldBUSCAR.getText();
        filtroS.setRowFilter(RowFilter.regexFilter(jTextFieldBUSCAR.getText(), 0));
    }

    private void generarTablaVenta() {
        tablaVenta.setRowCount(0);
        for (String[] datos : listaVenta) {
            tablaVenta.addRow(datos);
        }
        jTableProductosVenta.setModel(tablaVenta);
        //System.out.println(Arrays.deepToString(PRODUCTO_CONTROLLER.mostarProductoTabla().toArray()));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FACTURA;
    private javax.swing.JLabel TextNombreCliente;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCarrito;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCantidad1;
    private javax.swing.JLabel jLabelCedulaCliente;
    private javax.swing.JLabel jLabelFactura;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelNombre2;
    private javax.swing.JLabel jLabelNombreClienteP1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemAcercadeNosostros;
    private javax.swing.JMenuItem jMenuItemVentas;
    private javax.swing.JMenu jMenuSoporte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JSpinner jSpinnerCantidad;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableConsulta;
    private javax.swing.JTable jTableProductosVenta;
    private javax.swing.JTextField jTextFieldBUSCAR;
    private javax.swing.JTextField jTextFieldCC;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldNombreCliente;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldProducto;
    private javax.swing.JTextField jTextFieldTotal;
    private javax.swing.JTextField jTextFieldVenta;
    // End of variables declaration//GEN-END:variables
}
