package view;

import controller.ProductoController;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class MenuCotizacion extends javax.swing.JFrame {

    private final ProductoController PRODUCTO_CONTROLLER = new ProductoController();
    private final String[] Columnas = {"Producto".toUpperCase(), "Id Producto".toUpperCase(), "Descripcion".toUpperCase(), "Proveedor".toUpperCase(), "Categoria".toUpperCase(), "Cantidad".toUpperCase(),
        "Precio de compra".toUpperCase(), "Precio de venta".toUpperCase()};
    private final DefaultTableModel TABLA_DEFECTO = new DefaultTableModel(null, Columnas);
    private final String[] columnasVenta = {"Producto".toUpperCase(), "Precio de venta".toUpperCase(), "Cantidad".toUpperCase()};
    private final DefaultTableModel tablaVenta = new DefaultTableModel(null, columnasVenta);
    private ArrayList<String[]> listaVenta = new ArrayList<>();

    public TableRowSorter filtroS;
    String filtro;

    private MenuVenta ventanaVenta;

    public void setVentana(MenuVenta ventanaVenta) {
        this.ventanaVenta = ventanaVenta;
    }

    private MenuProveedor ventana;

    public void setVentana(MenuProveedor ventana) {
        this.ventana = ventana;
    }

    private MenuCotizacion ventanaCotizacion;

    public void setVentana(MenuCotizacion Cotizacion) {
        this.ventanaCotizacion = ventanaCotizacion;
    }

    public MenuCotizacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de inventario La Ermita".toUpperCase());
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Ico.png")).getImage());
        generarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelCedulaCliente = new javax.swing.JLabel();
        jTextFieldBUSCAR = new javax.swing.JTextField();
        jLabelCantidad1 = new javax.swing.JLabel();
        jSpinnerVenta = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jSpinnerCantidad = new javax.swing.JSpinner();
        jTextFieldCC = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsulta = new javax.swing.JTable();
        jLabelNombre1 = new javax.swing.JLabel();
        jTextFieldProducto = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonCotizacion = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonCarrito = new javax.swing.JButton();
        FACTURA = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelFactura = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProductosVenta = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldTotal1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextNombreCliente = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelNombreClienteP1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();
        jTextFieldNombreCliente1 = new javax.swing.JTextField();
        jLabelNombre2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItemVentas = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuSoporte = new javax.swing.JMenu();
        jMenuItemAcercadeNosostros = new javax.swing.JMenuItem();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCedulaCliente.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabelCedulaCliente.setText("CEDULA:");
        jPanel1.add(jLabelCedulaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 40));

        jTextFieldBUSCAR.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        jTextFieldBUSCAR.setForeground(new java.awt.Color(153, 153, 153));
        jTextFieldBUSCAR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBUSCAR.setText("BARRA DE BUSQUEDA");
        jTextFieldBUSCAR.setToolTipText("");
        jTextFieldBUSCAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldBUSCARMouseClicked(evt);
            }
        });
        jTextFieldBUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBUSCARActionPerformed(evt);
            }
        });
        jTextFieldBUSCAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBUSCARKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldBUSCAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 520, 30));

        jLabelCantidad1.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabelCantidad1.setText("CANTIDAD:");
        jPanel1.add(jLabelCantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));

        jSpinnerVenta.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10000000, 1));
        jPanel1.add(jSpinnerVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 220, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel10.setText("PRECIO DE VENTA:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 140, -1));

        jSpinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));
        jPanel1.add(jSpinnerCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 220, -1));

        jTextFieldCC.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jTextFieldCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCCActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 370, -1));

        jTableConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableConsulta);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 580, 120));

        jLabelNombre1.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabelNombre1.setText("PRODUCTO:");
        jPanel1.add(jLabelNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 40));

        jTextFieldProducto.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jPanel1.add(jTextFieldProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 370, -1));

        jButtonCancelar.setText("CANCELAR");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 120, -1));

        jButtonCotizacion.setText("COTIZACION");
        jButtonCotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCotizacionActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 130, -1));

        jButton3.setText("LIMPIAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 120, -1));

        jButtonCarrito.setText("CARRITO");
        jButtonCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarritoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 80, 30));

        FACTURA.setBackground(new java.awt.Color(255, 255, 255));
        FACTURA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        FACTURA.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 307, -1, -1));

        jLabelFactura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FACTURA.add(jLabelFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 638, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        FACTURA.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 307, -1, 193));

        jLabel1.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INFORMACION FACTURACION");
        jLabel1.setToolTipText("");
        FACTURA.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jTableProductosVenta.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTableProductosVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableProductosVenta);

        FACTURA.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 120, 300, 190));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jTextFieldPrecio.setEditable(false);
        jTextFieldPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPrecio.setText("0");
        jTextFieldPrecio.setFocusable(false);
        jTextFieldPrecio.setPreferredSize(new java.awt.Dimension(60, 25));
        jTextFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioActionPerformed(evt);
            }
        });

        jTextFieldTotal1.setEditable(false);
        jTextFieldTotal1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTotal1.setText("0");
        jTextFieldTotal1.setFocusable(false);
        jTextFieldTotal1.setPreferredSize(new java.awt.Dimension(60, 25));
        jTextFieldTotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotal1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TOTAL:");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("IVA:");

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PRECIO:");

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("15%");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(33, 33, 33))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        FACTURA.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 300, 200));

        TextNombreCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FACTURA.add(TextNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 2, 10)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(" ALM ERMITA AP LT A");
        FACTURA.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 180, -1));

        jLabelNombreClienteP1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabelNombreClienteP1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNombreClienteP1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        FACTURA.add(jLabelNombreClienteP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 290, 80));

        jPanel1.add(FACTURA, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 310, 500));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("CANTIDAD DISPONIBLE:");
        jLabel2.setPreferredSize(new java.awt.Dimension(55, 25));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 190, -1));

        jTextFieldCantidad.setEditable(false);
        jTextFieldCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCantidad.setFocusable(false);
        jTextFieldCantidad.setPreferredSize(new java.awt.Dimension(70, 25));
        jTextFieldCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 220, -1));

        jTextFieldNombreCliente1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jTextFieldNombreCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreCliente1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNombreCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 370, -1));

        jLabelNombre2.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabelNombre2.setText("CLIENTE:");
        jPanel1.add(jLabelNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 40));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel9.setText("MENU DE COTIZACION");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jTabbedPane1.addTab("Realizar Cotizacion", jPanel1);

        jMenu1.setText("Sistema");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("Cerrar Sistema");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar2.add(jMenu1);

        jMenu6.setText("Ventas / Cotizacion ");

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem7.setText("Menu Principal");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        jMenuItemVentas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemVentas.setText("Ventas");
        jMenuItemVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVentasActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemVentas);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Cotizacion");
        jMenuItem2.setToolTipText("");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);
        jMenu6.add(jSeparator3);

        jMenuBar2.add(jMenu6);

        jMenu5.setText("Proveedor ");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Abrir Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar2.add(jMenu5);

        jMenuSoporte.setText("Soporte");

        jMenuItemAcercadeNosostros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemAcercadeNosostros.setText("Acerca de nosostros");
        jMenuItemAcercadeNosostros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcercadeNosostrosActionPerformed(evt);
            }
        });
        jMenuSoporte.add(jMenuItemAcercadeNosostros);

        jMenuBar2.add(jMenuSoporte);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 884, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreCliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreCliente1ActionPerformed

    private void jTextFieldCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadActionPerformed

    private void jTextFieldTotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotal1ActionPerformed

    private void jTextFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioActionPerformed

    private void jButtonCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarritoActionPerformed
        int cantidadAVender = (int) jSpinnerCantidad.getValue();

        if (cantidadAVender == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese una cantidad válida");
        } else {
            try {
                int indice = jTableConsulta.getSelectedRow();
                if (indice == -1) {
                    JOptionPane.showMessageDialog(null, "Seleccione un producto de la tabla");
                    return;
                }

                if (jTextFieldNombreCliente1.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Introduzca nombre es obligatorio");
                    return;
                }

                if (jTextFieldCC.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "El campo de cédula del cliente no puede estar vacío");
                    return;
                }

                jLabelNombreClienteP1.setText("<html>"
                        + "<b>Nombre del cliente:</b><br>"
                        + jTextFieldNombreCliente1.getText()
                        + "<br><b>Cedula del cliente:</b><br>"
                        + jTextFieldCC.getText() + "</html>");

                int cantidadDisponible = Integer.parseInt(jTableConsulta.getValueAt(indice, 5).toString()); // Columna de cantidad
                if (cantidadAVender <= cantidadDisponible) {
                    listaVenta.add(new String[]{
                        jTextFieldProducto.getText(),
                        String.valueOf(jSpinnerVenta.getValue()),
                        String.valueOf(jSpinnerCantidad.getValue())
                    });
                    generarTablaVenta();

                    float precio = Float.parseFloat(jTextFieldPrecio.getText());
                    float costeProducto = Float.parseFloat(String.valueOf(jSpinnerVenta.getValue())) * cantidadAVender;
                    float nuevoPrecio = precio + costeProducto;
                    jTextFieldPrecio.setText(String.valueOf(nuevoPrecio));

                    float precioIVA = nuevoPrecio * 0.15f;
                    float precioTOTAL = nuevoPrecio + precioIVA;
                    jTextFieldTotal1.setText(String.valueOf(precioTOTAL));

                } else {
                    JOptionPane.showMessageDialog(null, "Cantidad insuficiente en inventario");
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonCarritoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextFieldCC.setText("");
        jTextFieldNombreCliente1.setText("");
        jTextFieldProducto.setText("");
        jSpinnerCantidad.setValue(0);
        jTextFieldCantidad.setText("");
        jSpinnerVenta.setValue(0);
        jLabelFactura.setText("");
        jTextFieldBUSCAR.setText("");
        jLabelNombreClienteP1.setText("");
        DefaultTableModel modelo = (DefaultTableModel) jTableProductosVenta.getModel();
        modelo.setRowCount(0);
        jTextFieldTotal1.setText("0.0");
        jTextFieldPrecio.setText("0.0");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        MenuPrincipal menu_principal = new MenuPrincipal();
        menu_principal.setVentana(menu_principal);
        menu_principal.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTableConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultaMouseClicked
        try {
            int indice = jTableConsulta.rowAtPoint(evt.getPoint());
            if (indice >= 0 && indice < jTableConsulta.getRowCount()) {
                jTextFieldProducto.setText(String.valueOf(jTableConsulta.getValueAt(indice, 0)));
                jTextFieldCantidad.setText(String.valueOf(jTableConsulta.getValueAt(indice, 5)));
                jSpinnerVenta.setValue(Integer.valueOf(jTableConsulta.getValueAt(indice, 7).toString()));

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al seleccionar el producto " + e.getMessage());
        }
    }//GEN-LAST:event_jTableConsultaMouseClicked

    private void jTextFieldCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCCActionPerformed

    private void jTextFieldBUSCARKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBUSCARKeyTyped
        filtroS = new TableRowSorter(jTableConsulta.getModel());
        jTableConsulta.setRowSorter(filtroS);
    }//GEN-LAST:event_jTextFieldBUSCARKeyTyped

    private void jTextFieldBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBUSCARActionPerformed

    }//GEN-LAST:event_jTextFieldBUSCARActionPerformed

    private void jTextFieldBUSCARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldBUSCARMouseClicked
        jTextFieldBUSCAR.setText("");
        try {
            jTextFieldBUSCAR.addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent e) {
                    try {
                        String cadena = jTextFieldBUSCAR.getText();
                        jTextFieldBUSCAR.setText(cadena);
                        repaint();
                        filtro();
                    } catch (Exception ex) {
                        System.out.println(ex.getMessage());
                    }
                }

            });
        } catch (Exception e) {
            e.printStackTrace(); // Imprime la excepción si ocurre al agregar el KeyListener
        }
    }//GEN-LAST:event_jTextFieldBUSCARMouseClicked

    private void jButtonCotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCotizacionActionPerformed
        JOptionPane.showMessageDialog(this, "COTIZACION HA SIDO REALIZADA");
    }//GEN-LAST:event_jButtonCotizacionActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JOptionPane.showMessageDialog(null, "CERRAR SESSION");
        LauncherSystem login = new LauncherSystem();
        login.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        MenuPrincipal menu_principal = new MenuPrincipal();
        menu_principal.setVentana(menu_principal);
        menu_principal.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItemVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVentasActionPerformed
        MenuVenta venta = new MenuVenta();
        venta.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItemVentasActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        MenuCotizacion Cotizacion = new MenuCotizacion();
        Cotizacion.setVentana(Cotizacion);
        Cotizacion.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        MenuProveedor Proveedor = new MenuProveedor();
        Proveedor.setVentana(Proveedor);
        Proveedor.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemAcercadeNosostrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcercadeNosostrosActionPerformed
        JOptionPane.showMessageDialog(null, "GRACIAS POR CONFIAR EN NOSOTROS");
    }//GEN-LAST:event_jMenuItemAcercadeNosostrosActionPerformed

    private void generarTabla() {
        TABLA_DEFECTO.setRowCount(0);
        for (String[] datos : PRODUCTO_CONTROLLER.mostarProductoTabla()) {
            TABLA_DEFECTO.addRow(datos);
        }
        jTableConsulta.setModel(TABLA_DEFECTO);
        System.out.println(Arrays.deepToString(PRODUCTO_CONTROLLER.mostarProductoTabla().toArray()));
    }

    public void filtro() {
        filtro = jTextFieldBUSCAR.getText();
        filtroS.setRowFilter(RowFilter.regexFilter(jTextFieldBUSCAR.getText(), 0));
    }

    private void generarTablaVenta() {
        tablaVenta.setRowCount(0);
        for (String[] datos : listaVenta) {
            tablaVenta.addRow(datos);
        }
        jTableProductosVenta.setModel(tablaVenta);
        //System.out.println(Arrays.deepToString(PRODUCTO_CONTROLLER.mostarProductoTabla().toArray()));
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FACTURA;
    private javax.swing.JLabel TextNombreCliente;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCarrito;
    private javax.swing.JButton jButtonCotizacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCantidad1;
    private javax.swing.JLabel jLabelCedulaCliente;
    private javax.swing.JLabel jLabelFactura;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelNombre2;
    private javax.swing.JLabel jLabelNombreClienteP1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItemAcercadeNosostros;
    private javax.swing.JMenuItem jMenuItemVentas;
    private javax.swing.JMenu jMenuSoporte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JSpinner jSpinnerCantidad;
    private javax.swing.JSpinner jSpinnerVenta;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableConsulta;
    private javax.swing.JTable jTableProductosVenta;
    private javax.swing.JTextField jTextFieldBUSCAR;
    private javax.swing.JTextField jTextFieldCC;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldNombreCliente1;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldProducto;
    private javax.swing.JTextField jTextFieldTotal1;
    // End of variables declaration//GEN-END:variables
}
