package view;

import controller.ProveedorController;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MenuProveedor extends javax.swing.JFrame {

    private final ProveedorController proveedorM = new ProveedorController();
    private final String[] Columnas = {"Nombre", "Identificacion", "Telefono", "Localizacion", "Corre Email", "Pago"};
    private final DefaultTableModel TABLA_DEFECTO = new DefaultTableModel(null, Columnas);

    private MenuProveedor ventana;

    public void setVentana(MenuProveedor ventana) {
        this.ventana = ventana;
    }

    public MenuProveedor() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de inventario La Ermita".toUpperCase());
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Ico.png")).getImage());
        generarTabla();

    }

    private void reiniciarFormulario() {
        jTextFieldnNombreProvedor.setText("");
        jSpinnerIdentificacionProveedor.setValue(0);
        jSpinnerTelefonoProveedor.setValue(0);
        jTextFieldDirrecionProveedor.setText("");
        jTextFieldEmailProvedor.setText("");
        jComboBoxPagosProveedor.setSelectedIndex(0);

    }

    private void generarTabla() {
        TABLA_DEFECTO.setRowCount(0);
        for (String[] datos : proveedorM.mostrarProveedorTabla()) {
            TABLA_DEFECTO.addRow(datos);
        }
        jTableProveedor.setModel(TABLA_DEFECTO);
        System.out.println(Arrays.deepToString(proveedorM.mostrarProveedorTabla().toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();
        jLabelProveedor = new javax.swing.JLabel();
        jLabelProveedor2 = new javax.swing.JLabel();
        jLabelProveedor3 = new javax.swing.JLabel();
        jLabelProveedor4 = new javax.swing.JLabel();
        jTextFieldDirrecionProveedor = new javax.swing.JTextField();
        jTextFieldEmailProvedor = new javax.swing.JTextField();
        jSpinnerTelefonoProveedor = new javax.swing.JSpinner();
        jSpinnerIdentificacionProveedor = new javax.swing.JSpinner();
        jTextFieldnNombreProvedor = new javax.swing.JTextField();
        jComboBoxPagosProveedor = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProveedor = new javax.swing.JTable();
        jPanelGuardarProveedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelActualizarProveedor = new javax.swing.JPanel();
        jLabel2Actualizar = new javax.swing.JLabel();
        jPanelEliminarProveedor = new javax.swing.JPanel();
        jLabelEliminar = new javax.swing.JLabel();
        jPanelRegresarMenu = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItemVentas = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuSoporte = new javax.swing.JMenu();
        jMenuItemAcercadeNosostros = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GESTION DE PROVEEDORES");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 40));

        jLabelNombre.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabelNombre.setText("NOMBRE:");
        jLabelNombre.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        jLabelDescripcion.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabelDescripcion.setText("IDENTIFICACION:");
        jLabelDescripcion.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.add(jLabelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 140, -1));

        jLabelProveedor.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabelProveedor.setText("PAGO:");
        jLabelProveedor.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.add(jLabelProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 60, -1));

        jLabelProveedor2.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabelProveedor2.setText("DIRRECION:");
        jLabelProveedor2.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.add(jLabelProveedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        jLabelProveedor3.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabelProveedor3.setText("TELEFONO:");
        jLabelProveedor3.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.add(jLabelProveedor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabelProveedor4.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabelProveedor4.setText("CORREO EMAIL: ");
        jLabelProveedor4.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.add(jLabelProveedor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 140, 20));

        jTextFieldDirrecionProveedor.setPreferredSize(new java.awt.Dimension(50, 25));
        jTextFieldDirrecionProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDirrecionProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldDirrecionProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 290, -1));

        jTextFieldEmailProvedor.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTextFieldEmailProvedor.setPreferredSize(new java.awt.Dimension(50, 25));
        jPanel1.add(jTextFieldEmailProvedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 290, -1));

        jSpinnerTelefonoProveedor.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(0L), Long.valueOf(0L), Long.valueOf(3900000000L), Long.valueOf(1L)));
        jSpinnerTelefonoProveedor.setPreferredSize(new java.awt.Dimension(50, 25));
        jPanel1.add(jSpinnerTelefonoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 280, 25));

        jSpinnerIdentificacionProveedor.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(0L), Long.valueOf(0L), Long.valueOf(3900000000L), Long.valueOf(1L)));
        jSpinnerIdentificacionProveedor.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinnerIdentificacionProveedor, ""));
        jSpinnerIdentificacionProveedor.setPreferredSize(new java.awt.Dimension(50, 25));
        jPanel1.add(jSpinnerIdentificacionProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 240, -1));

        jTextFieldnNombreProvedor.setPreferredSize(new java.awt.Dimension(50, 25));
        jPanel1.add(jTextFieldnNombreProvedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 300, -1));

        jComboBoxPagosProveedor.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jComboBoxPagosProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Selecione una opcion", "Efectivo", "Tarjetas de Credito y Debito", "Transferencias Bancarias y PSE" }));
        jComboBoxPagosProveedor.setPreferredSize(new java.awt.Dimension(50, 25));
        jPanel1.add(jComboBoxPagosProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 290, -1));

        jTableProveedor.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jTableProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProveedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProveedor);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 860, 150));

        jPanelGuardarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelGuardarProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelGuardarProveedorMouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GUARDAR");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelGuardarProveedorLayout = new javax.swing.GroupLayout(jPanelGuardarProveedor);
        jPanelGuardarProveedor.setLayout(jPanelGuardarProveedorLayout);
        jPanelGuardarProveedorLayout.setHorizontalGroup(
            jPanelGuardarProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGuardarProveedorLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanelGuardarProveedorLayout.setVerticalGroup(
            jPanelGuardarProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGuardarProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelGuardarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 120, -1));

        jPanelActualizarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel2Actualizar.setText("ACTUALIZAR");
        jLabel2Actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2ActualizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelActualizarProveedorLayout = new javax.swing.GroupLayout(jPanelActualizarProveedor);
        jPanelActualizarProveedor.setLayout(jPanelActualizarProveedorLayout);
        jPanelActualizarProveedorLayout.setHorizontalGroup(
            jPanelActualizarProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelActualizarProveedorLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel2Actualizar)
                .addGap(21, 21, 21))
        );
        jPanelActualizarProveedorLayout.setVerticalGroup(
            jPanelActualizarProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActualizarProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2Actualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelActualizarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        jPanelEliminarProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelEliminar.setText("ELIMINAR");
        jLabelEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelEliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelEliminarProveedorLayout = new javax.swing.GroupLayout(jPanelEliminarProveedor);
        jPanelEliminarProveedor.setLayout(jPanelEliminarProveedorLayout);
        jPanelEliminarProveedorLayout.setHorizontalGroup(
            jPanelEliminarProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEliminarProveedorLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabelEliminar)
                .addGap(21, 21, 21))
        );
        jPanelEliminarProveedorLayout.setVerticalGroup(
            jPanelEliminarProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEliminarProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelEliminarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, -1, -1));

        jPanelRegresarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelRegresarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRegresarMenuMouseClicked(evt);
            }
        });

        jLabel4.setText("REGRESAR");

        javax.swing.GroupLayout jPanelRegresarMenuLayout = new javax.swing.GroupLayout(jPanelRegresarMenu);
        jPanelRegresarMenu.setLayout(jPanelRegresarMenuLayout);
        jPanelRegresarMenuLayout.setHorizontalGroup(
            jPanelRegresarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegresarMenuLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(21, 21, 21))
        );
        jPanelRegresarMenuLayout.setVerticalGroup(
            jPanelRegresarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegresarMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelRegresarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 860, -1));

        jMenu2.setText("Sistema");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("Cerrar Sistema");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu6.setText("Ventas / Cotizacion ");

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem7.setText("Menu Principal");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        jMenuItemVentas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemVentas.setText("Ventas");
        jMenuItemVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVentasActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemVentas);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Cotizacion");
        jMenuItem2.setToolTipText("");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);
        jMenu6.add(jSeparator3);

        jMenuBar1.add(jMenu6);

        jMenu5.setText("Proveedor ");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Abrir Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        jMenuSoporte.setText("Soporte");

        jMenuItemAcercadeNosostros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemAcercadeNosostros.setText("Acerca de nosostros");
        jMenuItemAcercadeNosostros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcercadeNosostrosActionPerformed(evt);
            }
        });
        jMenuSoporte.add(jMenuItemAcercadeNosostros);

        jMenuBar1.add(jMenuSoporte);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDirrecionProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDirrecionProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDirrecionProveedorActionPerformed

    private void jPanelRegresarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRegresarMenuMouseClicked
        MenuPrincipal Principal = new MenuPrincipal();
        Principal.setVisible(true);
        this.setVisible(false);
        this.dispose();

    }//GEN-LAST:event_jPanelRegresarMenuMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        try {
            String nombre = jTextFieldnNombreProvedor.getText();
            long identificacion = ((Number) jSpinnerIdentificacionProveedor.getValue()).longValue();
            long telefono = ((Number) jSpinnerTelefonoProveedor.getValue()).longValue();
            String direccion = jTextFieldDirrecionProveedor.getText();
            String correo = jTextFieldEmailProvedor.getText();
            String pago = (String) jComboBoxPagosProveedor.getSelectedItem();

            if (proveedorM.validarFormulario(nombre, identificacion, telefono, direccion, correo, pago)) {
                if (proveedorM.existeProveedor(nombre)) {
                    JOptionPane.showMessageDialog(this, "El proveedor " + nombre + " ya existe.");
                } else {
                    proveedorM.proveedor_model.setNombre(nombre);
                    proveedorM.proveedor_model.setIdentificacion(identificacion);
                    proveedorM.proveedor_model.setTelefono(telefono);
                    proveedorM.proveedor_model.setDireccion(direccion);
                    proveedorM.proveedor_model.setCorreo(correo);
                    proveedorM.proveedor_model.setPago(pago);
                    proveedorM.crearArchivoProveedor(proveedorM.proveedor_model, nombre);

                    reiniciarFormulario();
                    generarTabla();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error en el formato de los números: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jPanelGuardarProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGuardarProveedorMouseClicked

    }//GEN-LAST:event_jPanelGuardarProveedorMouseClicked

    private void jLabelEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelEliminarMouseClicked
        try {
            String nombre = jTextFieldnNombreProvedor.getText();
            if (!nombre.isEmpty()) {
                proveedorM.eliminarArchivoProveedor(nombre);
                reiniciarFormulario();
                generarTabla();
            } else {
                JOptionPane.showMessageDialog(this, "Ingrese su identificacion: ");
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jLabelEliminarMouseClicked

    private void jTableProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProveedorMouseClicked
        try {
            int indice = jTableProveedor.rowAtPoint(evt.getPoint());
            if (indice >= 0 && indice < jTableProveedor.getRowCount()) {
                jTextFieldnNombreProvedor.setText(String.valueOf(jTableProveedor.getValueAt(indice, 0)));
                jSpinnerIdentificacionProveedor.setValue(Integer.valueOf(jTableProveedor.getValueAt(indice, 1).toString()));
                jSpinnerTelefonoProveedor.setValue(Long.valueOf(jTableProveedor.getValueAt(indice, 2).toString()));
                jTextFieldDirrecionProveedor.setText(String.valueOf(jTableProveedor.getValueAt(indice, 3)));
                jTextFieldEmailProvedor.setText(String.valueOf(jTableProveedor.getValueAt(indice, 4)));
                jComboBoxPagosProveedor.setSelectedItem(String.valueOf(jTableProveedor.getValueAt(indice, 5)));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al seleccionar el proveedor: " + e.getMessage());
        }
    }//GEN-LAST:event_jTableProveedorMouseClicked

    private void jLabel2ActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2ActualizarMouseClicked
        try {
            String nombre = jTextFieldnNombreProvedor.getText();
            long identificacion = ((Number) jSpinnerIdentificacionProveedor.getValue()).longValue();
            long telefono = ((Number) jSpinnerTelefonoProveedor.getValue()).longValue();
            String direccion = jTextFieldDirrecionProveedor.getText();
            String correo = jTextFieldEmailProvedor.getText();
            String pago = (String) jComboBoxPagosProveedor.getSelectedItem();

            // Validar si los campos no están vacíos y son correctos
            if (proveedorM.validarFormulario(nombre, identificacion, telefono, direccion, correo, pago)) {
                if (!proveedorM.existeProveedor(nombre)) {
                    JOptionPane.showMessageDialog(this, "El proveedor " + nombre + " no existe.");
                } else {
                    proveedorM.proveedor_model.setNombre(nombre);
                    proveedorM.proveedor_model.setIdentificacion(identificacion);
                    proveedorM.proveedor_model.setTelefono(telefono);
                    proveedorM.proveedor_model.setDireccion(direccion);
                    proveedorM.proveedor_model.setCorreo(correo);
                    proveedorM.proveedor_model.setPago(pago);
                    proveedorM.actualizarArchivoProveedor(proveedorM.proveedor_model, nombre);

                    reiniciarFormulario();
                    generarTabla();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error en el formato de los números: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_jLabel2ActualizarMouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JOptionPane.showMessageDialog(null, "CERRAR SESSION");
        LauncherSystem login = new LauncherSystem();
        login.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        MenuPrincipal menu_principal = new MenuPrincipal();
        menu_principal.setVentana(menu_principal);
        menu_principal.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItemVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVentasActionPerformed
        MenuVenta venta = new MenuVenta();
        venta.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItemVentasActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        MenuCotizacion Cotizacion = new MenuCotizacion();
        Cotizacion.setVentana(Cotizacion);
        Cotizacion.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        MenuProveedor Proveedor = new MenuProveedor();
        Proveedor.setVentana(Proveedor);
        Proveedor.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemAcercadeNosostrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcercadeNosostrosActionPerformed
        JOptionPane.showMessageDialog(null, "GRACIAS POR CONFIAR EN NOSOTROS");
    }//GEN-LAST:event_jMenuItemAcercadeNosostrosActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxPagosProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2Actualizar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelEliminar;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelProveedor;
    private javax.swing.JLabel jLabelProveedor2;
    private javax.swing.JLabel jLabelProveedor3;
    private javax.swing.JLabel jLabelProveedor4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItemAcercadeNosostros;
    private javax.swing.JMenuItem jMenuItemVentas;
    private javax.swing.JMenu jMenuSoporte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelActualizarProveedor;
    private javax.swing.JPanel jPanelEliminarProveedor;
    private javax.swing.JPanel jPanelGuardarProveedor;
    private javax.swing.JPanel jPanelRegresarMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JSpinner jSpinnerIdentificacionProveedor;
    private javax.swing.JSpinner jSpinnerTelefonoProveedor;
    private javax.swing.JTable jTableProveedor;
    private javax.swing.JTextField jTextFieldDirrecionProveedor;
    private javax.swing.JTextField jTextFieldEmailProvedor;
    private javax.swing.JTextField jTextFieldnNombreProvedor;
    // End of variables declaration//GEN-END:variables

}
